### ISSUE TITLE
aur package breakage

### ISSUE THREAD

**Issue by ninrod** [ttzhou/setroot#13]
hi @ttzhou and thanks for the program!

I'm getting this after trying to install `setroot` tonight on arch with `pacaur -S setroot`:

```sh
==> Finished making: setroot v2.0.gb4a4607-1 (Sun Sep 3 12:03:36 -03 2017)
==> Cleaning up...
:: Installing setroot package(s)...
:: setroot package(s) failed to install.
:: ensure package version does not mismatch between .SRCINFO and PKGBUILD
:: ensure package name has a VCS suffix if this is a devel package
:: imlib2 is now an orphan package
```

**Comment by vyp** [comment]
Is there a way to make pacaur say why it failed to install?

**Comment by ninrod** [comment]
hum, beyond this log snippet, not that I know of.

**Comment by vyp** [comment]
Hmm that's not very helpful... 😕

I don't know much about Arch so the only other thing I can think of right now is to perhaps try installing the AUR package manually, and see if there's any errors that arise from trying to do that? I'm not sure if how straightforward installing without a helper is though?

**Comment by ninrod** [comment]
yes @vyp, this is a good idea. A number of issues are pointing to a problem in PACAUR:

https://github.com/rmarquis/pacaur/issues/414
https://github.com/rmarquis/pacaur/issues/419

But I'm not sure. I'll try to manually install it tonight using just `makepkg -sri`.

**Comment by ttzhou** [comment]
I finally got off my ass and tried to resolve this; PKGBUILD was using commit hash and I've changed it to use tags instead. 

I tested with `yay` and it seems to work. Closing - feel free to reopen if it fails with some other AUR helper.
