### ISSUE TITLE
imlib2-config not found

### ISSUE THREAD

**Issue by TheMohawkNinja** [ttzhou/setroot#17]
Hello,

Attempting to build with `sudo make xinerama=0` results in `/bin/sh: line 1: imlib2-config: command not found`.

SOLUTION:

Per https://githubplus.com/auerswal/ssocr/issues/17 Makefile line 9 should have `pkg-config --libs imlib2` after the `-lX11` flag instead of `imlib2-config --libs`.

**Comment by ttzhou** [comment]
Would this PR address it: https://github.com/ttzhou/setroot/pull/16

I admit I have not looked at my project in ages 😅

**Comment by TheMohawkNinja** [comment]
> Would this PR address it: #16
> 
> I admit I have not looked at my project in ages sweat_smile

Yup, that pull request contains my requested fix :)

And no worries, I just happened to find your project when looking up barebones examples on how to set wallpapers in a multihead configuration.

**Comment by ttzhou** [comment]
Just merged that PR. lmk if resolves.

**Comment by TheMohawkNinja** [comment]
> Just merged that PR. lmk if resolves.

Yup, that seems to have done it.
