### ISSUE TITLE
Broken AUR package

### ISSUE THREAD

**Issue by AtomToast** [ttzhou/setroot#19]
The AUR package has been broken for quite some time now. The latest change (~5 years ago) to the package broke the pkgver() function. It doesn't replace the illegal hyphens.

I suggest fixing it by replacing the git command with `git describe --long --tags --abbrev=7 | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'` as per the [arch wiki](https://wiki.archlinux.org/title/VCS_package_guidelines#The_pkgver()_function)

**Comment by ttzhou** [comment]
acked, thanks for raising and providing fix. pretty busy atm but I'll see if I can find some time soon to try and patch.

**Comment by ttzhou** [comment]
@AtomToast pushed some changes to AUR. I have not used AUR in forever, but I can run `makepkg` locally so maybe that should do it. 

lmk if resolved

**Comment by AtomToast** [comment]
Can confirm that the package is fixed. However the package is still missing the `s/^v//` part. Which is not a huge deal imo but according to the wiki directions:

> If tag contains a prefix, like v or project name then it should be cut off

**Comment by ttzhou** [comment]
> Can confirm that the package is fixed. However the package is still missing the `s/^v//` part. Which is not a huge deal imo but according to the wiki directions:
> 
> > If tag contains a prefix, like v or project name then it should be cut off

ugh - thanks for calling that out. I'll adjust AUR side when i have a second. thanks for keeping me honest.

**Comment by ttzhou** [comment]
done
