### ISSUE TITLE
ESETROOT_PMAP_ID atom instead of ESETROOTPMAP_ID

### ISSUE THREAD

**Issue by MrCatNerd** [ttzhou/setroot#20]
in line 106 and 130 (setroot.c), setroot is fetching the wrong atom from the x server, ESETROOTPMAP_ID, but it should be ESETROOT_PMAP_ID, setroot still works because it sets _XROOTPMAP_ID too

**Comment by ttzhou** [comment]
speak of the devil. could have sworn it was ESETROOTPMAP_ID all those years ago in upstream, but yeah, looks like it got swapped. I'll fix at some point. Also would welcome a PR, should be easy fix as well if I take too long.

**Comment by ttzhou** [comment]
https://github.com/ttzhou/setroot/pull/21

if you want to take a peek
