### ISSUE TITLE
Solid Color Flag not Working

### ISSUE THREAD

**Issue by angelic-sedition** [ttzhou/setroot#9]
From my understanding, the --solid-color flag should take a hex colour code including "#" and set the background to it. When I try `setroot --solid-color "#ff0000"`, I get the error "Image #ff0000 not found."  `setroot --solid-color ff0000` gives this error:
```
Invalid color ff0000; defaulting to black.
Image ff0000 not found.
```

To see if it would work if an image was provided, I tried other commands, but I always get errors. I get the first error when trying `setroot big.jpg --solid-color "#ff0000"` or `setroot --solid-color "#ff0000" big.jpg` or `setroot --solid-color \#ff0000`. However, if I try `setroot --solid-color big.jpg "#ff0000"`, I get the second error:
```
Invalid color big.jpg; defaulting to black.
Image #ff0000 not found.
```

**Comment by ttzhou** [comment]
I can reproduce. Taking a look, likely an argument count error.

**Comment by ttzhou** [comment]
can you test latest commit? (unfortunately I now have one spot in the code with three levels of indentation - sorry Mr. Torvalds).

**Comment by angelic-sedition** [comment]
Haha, thanks a ton! It's working fine now.
